# Generated by Django 3.0.2 on 2020-01-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_id',
        ),
    ]
