# Generated by Django 3.0.2 on 2020-01-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_remove_like_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
